let x = 1;

try {
  x = 1;
} catch (error) {
  throw error;
}
